////////////////////////////////////////////////////////////////////////
// Class:       POTCounter
// Module Type: analyzer
// File:        POTCounter_module.cc
//
// Generated at Fri Feb  1 07:10:04 2019 by Joris De vries using artmod
// from cetpkgsupport v1_14_01.
////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDAnalyzer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "canvas/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"

namespace pot_counter {

class POTCounter;

class POTCounter : public art::EDAnalyzer {
public:
  explicit POTCounter(fhicl::ParameterSet const & p);
  // The destructor generated by the compiler is fine for classes
  // without bare pointers or other resource use.

  // Plugins should not be copied or assigned.
  POTCounter(POTCounter const &) = delete;
  POTCounter(POTCounter &&) = delete;
  POTCounter & operator = (POTCounter const &) = delete;
  POTCounter & operator = (POTCounter &&) = delete;

  // Required functions.
  void analyze(art::Event const & e) override;


private:

  // Declare member data here.

};


POTCounter::POTCounter(fhicl::ParameterSet const & p)
  :
  EDAnalyzer(p)  // ,
 // More initializers here.
{}

void POTCounter::analyze(art::Event const & e)
{
  // Implementation of required member function here.
  std::cout << "My module on event #" << e.id().event() << std::endl;
}

} // tutorial namespace 

DEFINE_ART_MODULE(POTCounter)
